# Generated by Django 3.2.18 on 2023-02-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(max_length=50, verbose_name='Mensaje'),
        ),
    ]
